### ISSUE TITLE
Update each yml file to contain the webapp name in the top name field.

### ISSUE THREAD

**Issue by nertim** [Azure/actions-workflow-templates#3]
current
name: Build and deploy JAR app to Azure Web App

should be
name: Build and deploy JAR app to Azure Web App ${web-app-name}

**Comment by N-Usha** [comment]
@nertim - Web-app-name is available only after the name of the workflow is processed. Can you please confirm the variable to use for web-app-name in case if you have tried this in any workflow?
Coz I tried with ${{ env.AZURE_WEBAPP_NAME }} and the workflow simply failed : https://github.com/N-Usha/nodejs-shopping-cart/actions

**Comment by JasonFreeberg** [comment]
@N-Usha These are just template files, so anything in wrapped in a `${ ... }` is meant to be interpolated by the client (Portal or CLI), not an environment variable. 

For example, [this line](https://github.com/Azure/actions-workflow-templates/blob/cccc0443287314ddf7bd5789cd0af4ebeed202da/AppService/linux/java-jar-webapp-on-azure.yml#L27) has a nested `${ ... }` because that inner portion will be replaced by the client.
